// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI (migrate, generate) prefers DIRECT_URL when set, because Supabase's
    // transaction pooler on port 6543 strips advisory locks + prepared statements that
    // the migration engine needs. App runtime reads DATABASE_URL directly via
    // src/lib/prisma.ts and is unaffected by this.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
